services:
  # Service pour Symfony (Backend)
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: symfony_backend
    working_dir: /var/www/html
    volumes:
      - ./Backend:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - symfony-network
    depends_on:
      - db

  # Service pour Frontend (Angular)
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: angular_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./Frontend:/app
    networks:
      - symfony-network
    depends_on:
      - backend

  # Service pour MySQL
  db:
    image: mysql:5.7
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony-network

  # Service Nginx pour Symfony (Backend)
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - ./server/nginx1.conf:/etc/nginx/nginx.conf
      - ./Backend:/var/www/html
    ports:
      - "9001:80"  # Remplace le port pour le backend, par exemple 9001
    depends_on:
      - backend
    networks:
      - symfony-network


volumes:
  mysql_data:

networks:
  symfony-network:
    driver: bridge
